language: php

matrix:
  include:
    - php: 7.1
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev

before_install:
  - composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:1.*
  - composer install --dev
 
script:
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
 
after_script:
  - php vendor/bin/coveralls -v
